### ISSUE TITLE
Specify which summer term a course is offered in

### ISSUE THREAD

**Issue by matlois75** [Tsounguinzo/concordia-courses#23]
When I check for any summer course, the schedule is provided but not which summer term the course is offered. Summer courses are offered in term 1, term 2, or full summer (12 weeks), and this information should be provided to improve the usefulness of the site.

**Comment by Tsounguinzo** [comment]
fixed with commit https://github.com/Tsounguinzo/concordia-courses/commit/34ce0a709cedb0b2a5fd28848b5643f4d56b1b81
